### ISSUE TITLE
Setting batch Size

### ISSUE THREAD

**Issue by rays2pix** [qiexing/face-landmark-localization#16]
Hi, Is it possible to change the batch size for caffe in your prediction script? Will it be faster than running the net once for every image?

**Comment by qiexing** [comment]
@rays2pix I think is possible, need to change the prediction code and prototxt.

**Comment by rays2pix** [comment]
@qiexing thanks. It worked. I was earlier trying to reshape in python,that didnt work. But modifying prototxt worked.
