### ISSUE TITLE
How to demarcate the "Roll","Yaw"and "Pitch" in the training set?

### ISSUE THREAD

**Issue by kylinly** [qiexing/face-landmark-localization#2]
How to demarcate the "Roll","Yaw"and "Pitch" in the training set? How many samples in your training set? Thank you!

**Comment by qiexing** [comment]
It's responsible for 3d head pose, you can google to know the difference between. I  use the data set from ibug300w. About 3800+ image for training .

**Comment by kylinly** [comment]
Thank you for the reply. The image set of  "ibug300w" gives 68 key points of the face, but not offer the   angle of "Roll,Yaw, and Pitch".So, How to get the three angles from "ibug300w" and using the three angles for training?

**Comment by kylinly** [comment]
Closed?

**Comment by Benuraj** [comment]
@kylinly were you able to figure out how to get angles with landmark points?
