### ISSUE TITLE
instruction of training

### ISSUE THREAD

**Issue by kaishijeng** [qiexing/face-landmark-localization#3]
Your pre-trained model performance is quite good. Can you provide info of how you train your net?

Thanks

**Comment by qiexing** [comment]
I prepare data ,then fine-tuning the vgg_s caffe model

**Comment by kaishijeng** [comment]
Which data set do you use to generate a pre-trained model?
Can you share you training script?

Thanks,

**Comment by qiexing** [comment]
I use ibug 300w 68 landmark

**Comment by kaishijeng** [comment]
I have downloaded ibug 300W 68 dataset. Do you mind sharing your training
scripts and solver.protobuf?

Thanks,

**Comment by kaishijeng** [comment]
QieXing

    Are you willing to share train.prototxt and solver.prototxt for training purpose?

Thanks

**Comment by affromero** [comment]
@kaishijeng did you have success reproducing @qiexing results? I've tried to without success. I performed translations and rotations over the 135 original files, as it was suggested, but the model overfit. 

I've done this [here](https://github.com/affromero/ActionUnits_Classification/blob/master/Landmarks/face-landmark-localization/get_data.py)  in case you want to take a look and try yourself in case you have not.

**Comment by kaishijeng** [comment]
@Afromero

I tried, but not able to make it work. I will take a look at what you have
done.


Thanks,

**Comment by kaishijeng** [comment]
@Afromero,

    Did you have a luck of getting  training worked? Your github repository
 mentions it is still overfitting.

**Comment by affromero** [comment]
No @kaishijeng, I have not. I even improved from 135 images to 1M images performing rotations from -80 to 80 degrees and translations and now it does not learn at all, I'm playing with the parameters by now to see what happens. 

I hope @qiexing could give us a hand.

**Comment by kaishijeng** [comment]
@Afromero

   Thanks for the update. Let us  hope qlexing reads this and shares his
training code.
