### ISSUE TITLE
制作HDF5数据请教

### ISSUE THREAD

**Issue by ustcluq** [qiexing/face-landmark-localization#33]
请问制作hdf5数据的时候，1）、像素减均值了吗？
                                          2）、另外特征点的坐标需要归一化吗？

可以方便给一个制作源码吗，谢谢！

**Comment by qiexing** [comment]
@ustcluq 都有。可以看下这个https://github.com/qiexing/caffe-regression/blob/master/kaggle_fkp_data/kfkd.py 文件，第30行和35行。

**Comment by ustcluq** [comment]
好的，非常感谢大神赐教！
我把数据按照您的方法做好后，loss一直是9.2左右，从一开始迭代就是这个值，我把测试结果打出来看了一下，输出的每张图像136个值都一样，并且在图像上显示的全是人脸最中间的一列。我把lr从0.1依次改到0.0000001都不行，请大神再指导一下呗，万分感谢！！

**Comment by qiexing** [comment]
@ustcluq 可以参考下https://github.com/qiexing/face-landmark-localization/issues/24

**Comment by ustcluq** [comment]
@qiexing 谢谢这么快回复！
我照着您说的改了，效果还是那样。我正在尝试其他方法~

**Comment by ustcluq** [comment]
@qiexing 我加了预训练模型，现在已经收敛，多谢！
