### ISSUE TITLE
Request train dataset

### ISSUE THREAD

**Issue by zhoupan9109** [qiexing/face-landmark-localization#41]
Thanks for author excellent work!

In my research, I need train the other net of face landmark detection. However, only training the single label dataset, I don't know how  augment the landmark label data to the format requested by caffe. Can anyone provide the asked dataset , only need little data, to help me learn how to augment multi labels data for caffe.

Thank you very much!

**Comment by qiexing** [comment]
@zhoupan9109 You can refer this project: https://github.com/qiexing/caffe-regression.
It has the train dataset and illustrates how to make the data for caffe.

**Comment by zhoupan9109** [comment]
@qiexing Thank you very much!
